services:
  glance-tasks-backend:
    build: .
    container_name: glance_google_calendar_backend
    ports:
      - "8075:8075"
    restart: always
    environment:
      - CLIENT_ID={REPLACE_ME}
      - CLIENT_SECRET={REPLACE_ME}
      - REFRESH_TOKEN={REPLACE_ME}
