server:
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  custom-css-file: /assets/user.css
  contrast-multiplier: 1.5
  primary-color: 0 100 47
  positive-color: 95 43 42
  negative-color: 0 100 33
  #text-saturation-multiplier: 1.5 

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
  #!include: redhat.yml
